"""Le MIE frasi, scritte da me: vere, semplici, umili. L'AI non le può modificare."""

FRASI: dict[str, str] = {
    "Python": "ho usato Python soprattutto per il testing: in Sellogic, con Playwright e pytest, ho scritto circa 70 test E2E e 226 test API",
    "Java": "ho una formazione Java (Master Epicode e JEE Academy) e in Java ho scritto i test mobile con Appium e una suite Selenium + Cucumber",
    "C#": "ho sviluppato in C# il backend del mio progetto principale, con 49 test API in xUnit",
    "JavaScript": "in Sellogic ho costruito in JavaScript una suite E2E con Cypress",
    "TypeScript": "ho usato TypeScript per il gestionale Angular del mio progetto principale",
    "Dart / Flutter": "in Sellogic ho iniziato come sviluppatrice Flutter su un'app di self-order",
    "SQL": "uso PostgreSQL nei miei progetti, con migration versionate",
    "Node.js": "conosco Node.js grazie a React, e in Sellogic ho fatto un po' di test sul backend Node usato dalle app kiosk in Flutter",
    "Django": "con Django ho sviluppato il mio portfolio online e un aggregatore di offerte di lavoro",
    "Spring Boot": "ho studiato Spring Boot nel Master Epicode e nella JEE Academy",
    "Hibernate / JPA": "ho usato JPA e Hibernate durante il Master Epicode e la JEE Academy",
    "Servlet / JSP": "ho lavorato con Servlet e JSP durante la JEE Academy",
    "ASP.NET Core": "ho sviluppato da sola una Web API in ASP.NET Core con Entity Framework e PostgreSQL",
    "Entity Framework": "ho usato Entity Framework Core con migration versionate nel mio progetto .NET",
    "Angular": "ho sviluppato il gestionale Angular del mio progetto principale",
    "React": "ho studiato React nel Master Full Stack di Epicode",
    "Vue": "in Sellogic ho testato per mesi un gestionale sviluppato in Vue 3",
    "HTML / CSS": "uso HTML e CSS nei frontend dei miei progetti",
    "Playwright": "in Sellogic ho migrato una suite da Cypress a Playwright e ho scritto 226 test API",
    "Cypress": "in Sellogic ho costruito da zero una suite E2E con Cypress",
    "Selenium": "ho scritto una suite Selenium + Cucumber di 53 scenari BDD su un gestionale Angular",
    "Appium": "in Sellogic ho automatizzato con Appium i test di 3 app native",
    "Robot Framework": "ho scritto 94 test E2E con Robot Framework sul mio progetto principale",
    "Cucumber / BDD": "scrivo scenari BDD in Gherkin con Cucumber, sia web sia mobile",
    "API REST": "in Sellogic ho scritto 226 test API e nel mio progetto ho sviluppato una Web API REST",
    "Test manuali": "in Sellogic ho fatto test manuali su ogni modulo del gestionale e segnalato i bug su Jira",
    "Docker": "uso Docker e Docker Compose nelle pipeline di test dei miei progetti",
    "GitLab CI": "in Sellogic ho configurato le pipeline di test su GitLab CI",
    "CI/CD": "ho configurato pipeline CI con GitLab CI e GitHub Actions",
    "Agile / Scrum": "ho lavorato con metodologie Agile durante il Master Epicode",
}